# DO NOT EDIT THIS FILE!
#
# Python module OpenHRP__POA generated by omniidl

import omniORB
omniORB.updateModule("OpenHRP__POA")

# ** 1. Stub files contributing to this module
import ModelLoader_idl
import OpenHRPCommon_idl

# ** 2. Sub-modules

# ** 3. End
